# 샘플로 테스트

In [1]:
import pandas as pd
import numpy as np

# 감정군 목록
all_emotions = ["love", "sadness", "anger", "hope", "surprise"]

# 데이터 불러오기
df = pd.read_pickle('../results/emotion_analysis.pkl')
sample_df = df.sample(1000, random_state=42)
sample_df.head()

,title,artist,genre,year,total_tokens,emotion_word_count,emotion_word_ratio,emotion_words,count_anger,ratio_anger,...,ratio_hope,count_love,ratio_love,count_sadness,ratio_sadness,count_surprise,ratio_surprise,emotion_score,normalized_emotion_score,emotion_score_detail
60141,Come Home,OneRepublic,rock,2007,84,20,23.81,"hope, forgive, missing, wrong, tired, long, lo...",4,4.76,...,4.76,5,5.95,12,14.29,1,1.19,-9.0,-0.450000,"{'hope': 4, 'surprise': 1, 'love': 5, 'sadness..."
51622,Cookin,"Fat Joe, Remy Ma & French Montana",rap,2016,158,18,11.39,"crack, bad, bitch, bitch, shoot, swear, trump,...",9,5.70,...,0.63,4,2.53,12,7.59,1,0.63,-16.5,-0.916667,"{'sadness': 12, 'anger': 9, 'love': 4, 'surpri..."
45618,Cant Let The Summer Pass,Murda Beatz,rb,2016,74,11,14.86,"murder, murder, pretty, time, ignore, ignore, ...",2,2.70,...,2.70,3,4.05,7,9.46,2,2.70,-5.0,-0.454545,"{'anger': 2, 'sadness': 7, 'surprise': 2, 'hop..."
51675,Boss Up,Tyga,rb,2017,137,23,16.79,"love, shot, pull, love, job, job, love, bitch,...",5,3.65,...,0.73,18,13.14,6,4.38,2,1.46,7.5,0.326087,"{'love': 18, 'anger': 5, 'sadness': 6, 'surpri..."
75723,If I Didn't Love You,Jason Aldean and Carrie Underwood,Unknown,2021,140,30,21.43,"long, crazy, baby, love, good, love, love, cry...",3,2.14,...,2.86,24,17.14,5,3.57,4,2.86,18.0,0.600000,"{'hope': 4, 'anger': 3, 'sadness': 5, 'love': ..."

In [2]:
emotion_count_cols = [
    'count_anger', 'count_hope', 'count_love', 'count_sadness', 'count_surprise'
]

emotion_ratio_cols = [
    'ratio_anger', 'ratio_hope', 'ratio_love', 'ratio_sadness', 'ratio_surprise'
]

## 장르별 분석

In [6]:
# Unknown 제외 데이터셋
df_genre = sample_df[sample_df['genre'] != 'Unknown']

In [7]:
# 장르별 감정군 Count / 비율
genre_emotion_count = df_genre.groupby('genre')[emotion_count_cols].sum()
genre_emotion_ratio = genre_emotion_count.div(genre_emotion_count.sum(axis=1), axis=0)

display(genre_emotion_count)
display(genre_emotion_ratio)

         count_anger  count_hope  count_love  count_sadness  count_surprise
genre
country           42          95         172            111              56
misc             454         584        1473           1022             293
pop             1118        1235        2388           2202             665
rap             8597        4947       10887          13276            3088
rb               449         441        1025            787             245
rock             816         827        1486           1731             458

         count_anger  count_hope  count_love  count_sadness  count_surprise
genre
country     0.088235    0.199580    0.361345       0.233193        0.117647
misc        0.118662    0.152640    0.384997       0.267120        0.076581
pop         0.146951    0.162329    0.313880       0.289432        0.087408
rap         0.210737    0.121265    0.266871       0.325432        0.075696
rb          0.152358    0.149644    0.347811       0.267051        0.083135
rock        0.153441    0.155510    0.279428       0.325498        0.086123

In [8]:
# 장르별 평균 emotion_score / normalized_emotion_score
genre_emotion_score = df_genre.groupby('genre')[['emotion_score', 'normalized_emotion_score']].mean()

display(genre_emotion_score)

         emotion_score  normalized_emotion_score
genre
country       3.694444                  0.178963
misc         12.041667                  0.055760
pop          -1.436073                 -0.010463
rap         -18.425325                 -0.328188
rb            0.130137                  0.052992
rock         -4.021739                 -0.147886

In [9]:
# emotion_words 컬럼 문자열 split → explode 처리
sample_explode = df_genre.assign(emotion_words=df_genre['emotion_words'].str.split(', ')).explode('emotion_words')

# 장르별 가장 많이 등장한 감정 단어 Top-10
genre_top10_words = (
    sample_explode.groupby('genre')['emotion_words']
    .value_counts()
    .groupby(level=0)
    .nlargest(10)
    .reset_index(level=0, drop=True)
)

display(genre_top10_words)

genre    emotion_words
country  time               19
         love               12
         baby                9
         good                6
         rest                6
         sun                 6
         kind                5
         leave               5
         wear                5
         alive               4
misc     time               71
         love               44
         good               27
         aunt               22
         long               22
         blue               19
         show               19
         smell              18
         joy                17
         wait               17
pop      love              266
         time              166
         baby              113
         good               58
         long               55
         bad                54
         feeling            47
         real               47
         friend             44
         show               44
rap      bitch            1323
         shit              953
         love              510
         time              458
         money             422
         baby              373
         real              331
         hit               298
         good              238
         god               231
rb       love              160
         baby              151
         time               89
         show               44
         shit               32
         bad                31
         friend             30
         feeling            28
         lie                28
         cry                24
rock     time              112
         love               80
         cry                39
         thought            39
         long               37
         hate               32
         friend             31
         good               31
         die                30
         leave              29
Name: count, dtype: int64

## 시대별 분석

In [15]:
# 연도를 10년 단위로 묶기 (Decade 컬럼 생성)
sample_df['decade'] = (sample_df['year'] // 10) * 10

In [16]:
# 시대별 감정군 Count / 비율
decade_emotion_count = sample_df.groupby('decade')[emotion_count_cols].sum()
decade_emotion_ratio = decade_emotion_count.div(decade_emotion_count.sum(axis=1), axis=0)

display(decade_emotion_count)
display(decade_emotion_ratio)

        count_anger  count_hope  count_love  count_sadness  count_surprise
decade
1980            125         148         394            274              79
1990            727         647        1222           1368             384
2000           1371         909        2256           2311             555
2010           8196        5923       12607          13536            3467
2020           1498         926        1946           2410             554

        count_anger  count_hope  count_love  count_sadness  count_surprise
decade
1980       0.122549    0.145098    0.386275       0.268627        0.077451
1990       0.167203    0.148804    0.281049       0.314627        0.088316
2000       0.185220    0.122805    0.304782       0.312213        0.074980
2010       0.187427    0.135448    0.288298       0.309543        0.079284
2020       0.204254    0.126261    0.265340       0.328606        0.075539

In [17]:
# 시대대별 평균 점수 변화
decade_emotion_score = sample_df.groupby('decade')[['emotion_score', 'normalized_emotion_score']].mean()

display(decade_emotion_score)

        emotion_score  normalized_emotion_score
decade
1980         2.300000                  0.129910
1990        -8.201493                 -0.078405
2000        -8.163866                 -0.133680
2010        -9.282380                 -0.174225
2020       -12.491667                 -0.272252

In [19]:
# emotion_words 컬럼 처리
df_explode = sample_df.assign(emotion_words=sample_df['emotion_words'].str.split(', ')).explode('emotion_words')

# 시대별 감정 단어 Top-N
top_n = 10
decade_top_words = (
    df_explode.groupby('decade')['emotion_words']
    .value_counts()
    .groupby(level=0)
    .nlargest(top_n)
    .reset_index(level=0, drop=True)
)

display(decade_top_words)

decade  emotion_words
1980    love               52
        baby               44
        talk               34
        time               26
        cry                17
        blame              11
        stranger           11
        cool               10
        cold                9
        dove                8
1990    love               91
        shit               74
        time               69
        baby               43
        bitch              42
        good               39
        real               33
        pray               30
        coming             28
        god                28
2000    love              190
        baby              147
        bitch             111
        shit              103
        time               97
        crazy              71
        bad                58
        gun                49
        word               49
        money              47
2010    bitch            1109
        love              789
        shit              735
        time              655
        baby              462
        money             377
        real              302
        good              279
        hit               227
        show              214
2020    bitch             170
        love              147
        shit              145
        time              107
        baby               85
        hit                75
        good               57
        real               55
        god                51
        bad                49
Name: count, dtype: int64

## 아티스트별 분석

In [12]:
# 상위 N명 아티스트 (곡 수 기준)
top_n = 20
top_artists = sample_df['artist'].value_counts().head(top_n).index.tolist()
df_top_artists = sample_df[sample_df['artist'].isin(top_artists)]

In [13]:
# 감정군별 평균 Count / 비율
artist_emotion_count = df_top_artists.groupby('artist')[emotion_count_cols].mean()
artist_emotion_ratio = artist_emotion_count.div(artist_emotion_count.sum(axis=1), axis=0)

# 아티스트별 평균 감정 점수
artist_emotion_score = df_top_artists.groupby('artist')[['emotion_score', 'normalized_emotion_score']].mean()

display(artist_emotion_count)
display(artist_emotion_ratio)
display(artist_emotion_score)

,count_anger,count_hope,count_love,count_sadness,count_surprise
artist,,,,,
$UICIDEBOY$,17.000000,6.250000,9.500000,21.500000,4.500000
2Pac,26.666667,10.666667,28.500000,42.666667,7.500000
A$AP Ferg,28.750000,13.500000,35.500000,40.000000,6.750000
BONES,6.750000,2.750000,7.500000,12.500000,1.750000
Bryson Tiller,4.000000,5.500000,12.750000,9.000000,2.500000
Chris Brown,4.000000,11.200000,20.600000,10.600000,5.200000
Drake,10.333333,8.000000,20.166667,18.000000,3.833333
J. Cole,14.000000,13.750000,25.000000,22.500000,6.000000
Kevin Gates,18.500000,8.500000,22.250000,31.250000,5.250000
Lil Wayne,24.285714,13.000000,34.000000,32.857143,8.857143
Lupe Fiasco,15.600000,11.200000,31.400000,25.400000,5.400000
Migos,21.200000,14.000000,30.800000,32.000000,5.400000
Nas,20.333333,11.000000,32.000000,33.000000,5.000000
Playboi Carti,22.000000,5.000000,8.500000,23.500000,1.750000
Rick Ross,22.428571,14.714286,27.714286,32.142857,7.428571
Taylor Swift,3.250000,7.500000,19.250000,10.250000,5.750000
The Game,24.750000,17.250000,34.000000,40.500000,10.250000
The Weeknd,10.000000,6.600000,12.000000,15.000000,4.400000
Trippie Redd,10.250000,5.750000,14.000000,12.500000,2.250000
Young Thug,23.500000,8.500000,18.000000,34.750000,8.000000

,count_anger,count_hope,count_love,count_sadness,count_surprise
artist,,,,,
$UICIDEBOY$,0.289362,0.106383,0.161702,0.365957,0.076596
2Pac,0.229885,0.091954,0.245690,0.367816,0.064655
A$AP Ferg,0.230924,0.108434,0.285141,0.321285,0.054217
BONES,0.216000,0.088000,0.240000,0.400000,0.056000
Bryson Tiller,0.118519,0.162963,0.377778,0.266667,0.074074
Chris Brown,0.077519,0.217054,0.399225,0.205426,0.100775
Drake,0.171271,0.132597,0.334254,0.298343,0.063536
J. Cole,0.172308,0.169231,0.307692,0.276923,0.073846
Kevin Gates,0.215743,0.099125,0.259475,0.364431,0.061224
Lil Wayne,0.214918,0.115044,0.300885,0.290771,0.078382
Lupe Fiasco,0.175281,0.125843,0.352809,0.285393,0.060674
Migos,0.205029,0.135397,0.297872,0.309478,0.052224
Nas,0.200658,0.108553,0.315789,0.325658,0.049342
Playboi Carti,0.362140,0.082305,0.139918,0.386831,0.028807
Rick Ross,0.214774,0.140903,0.265390,0.307798,0.071135
Taylor Swift,0.070652,0.163043,0.418478,0.222826,0.125000
The Game,0.195266,0.136095,0.268245,0.319527,0.080868
The Weeknd,0.208333,0.137500,0.250000,0.312500,0.091667
Trippie Redd,0.229050,0.128492,0.312849,0.279330,0.050279
Young Thug,0.253369,0.091644,0.194070,0.374663,0.086253

               emotion_score  normalized_emotion_score
artist
$UICIDEBOY$       -25.875000                 -0.735747
2Pac              -35.500000                 -0.467875
A$AP Ferg         -26.500000                 -0.428910
BONES             -10.375000                 -0.365887
Bryson Tiller       2.500000                  0.089432
Chris Brown        11.600000                  0.221277
Drake              -4.166667                 -0.115295
J. Cole            -4.625000                 -0.094845
Kevin Gates       -23.250000                 -0.351939
Lil Wayne         -16.642857                 -0.190063
Lupe Fiasco        -4.000000                 -0.081637
Migos             -15.400000                 -0.223780
Nas               -15.833333                 -0.132702
Playboi Carti     -34.500000                 -0.998154
Rick Ross         -19.500000                 -0.291968
Taylor Swift        9.500000                  0.374452
The Game          -22.625000                 -0.379748
The Weeknd         -9.700000                 -0.259628
Trippie Redd       -5.875000                 -0.206939
Young Thug        -36.000000                 -0.671680

In [20]:
# 상위 N명 아티스트만 대상으로 처리
top_artists = sample_df['artist'].value_counts().head(20).index.tolist()
df_top_artists = sample_df[sample_df['artist'].isin(top_artists)]

df_explode_artist = df_top_artists.assign(emotion_words=df_top_artists['emotion_words'].str.split(', ')).explode('emotion_words')

# 아티스트별 감정 단어 Top-N
top_n = 10
artist_top_words = (
    df_explode_artist.groupby('artist')['emotion_words']
    .value_counts()
    .groupby(level=0)
    .nlargest(top_n)
    .reset_index(level=0, drop=True)
)

display(artist_top_words)

artist       emotion_words
$UICIDEBOY$  stain            9
             gang             8
             bitch            6
             time             6
             grave            3
                             ..
Young Thug   gang             5
             bloody           4
             hood             4
             money            4
             neighborhood     4
Name: count, Length: 200, dtype: int64

In [21]:
# 특정 아티스트 감정 변화 추이
target_artist = 'Taylor Swift'  # 또는 'Eminem' 등
artist_df = sample_df[sample_df['artist'] == target_artist]

artist_decade_emotion = artist_df.groupby('decade')[emotion_count_cols].sum()
artist_decade_score = artist_df.groupby('decade')[['emotion_score', 'normalized_emotion_score']].mean()

display(artist_decade_emotion)
display(artist_decade_score)

        count_anger  count_hope  count_love  count_sadness  count_surprise
decade
2010             12          26          63             33              20
2020              1           4          14              8               3

        emotion_score  normalized_emotion_score
decade
2010        10.333333                  0.382603
2020         7.000000                  0.350000

# 전체에 적용

In [61]:
# module 패키지에서 필요한 함수 import
from module import (
    load_emotion_data,
    
    get_genre_emotion_count,
    get_genre_emotion_ratio,
    get_genre_emotion_score,
    get_genre_top_words,

    get_decade_emotion_count,
    get_decade_emotion_ratio,
    get_decade_emotion_score,
    get_decade_top_words,

    get_artist_emotion_count,
    get_artist_emotion_ratio,
    get_artist_emotion_score,
    get_artist_top_words,
    get_artist_emotion_trend
)

In [62]:
df = load_emotion_data('../results/emotion_analysis.pkl')
df.head()

,title,artist,genre,year,total_tokens,emotion_word_count,emotion_word_ratio,emotion_words,count_anger,ratio_anger,...,count_love,ratio_love,count_sadness,ratio_sadness,count_surprise,ratio_surprise,emotion_score,normalized_emotion_score,emotion_score_detail,decade
0,Rap God,Eminem,rap,2013,785,148,18.85,"[hurt, feeling, chance, wrong, slim, shady, fe...",49,6.24,...,70,8.92,79,10.06,19,2.42,-40.5,-0.273649,"{'anger': 49, 'sadness': 79, 'surprise': 19, '...",2010
1,WAP,Cardi B,rap,2020,314,48,15.29,"[whore, whore, whore, catch, extra, extra, nos...",18,5.73,...,22,7.01,22,7.01,11,3.50,-14.0,-0.291667,"{'anger': 18, 'sadness': 22, 'surprise': 11, '...",2020
2,Shape of You,Ed Sheeran,pop,2017,122,34,27.87,"[lover, friend, shot, drinking, talk, start, t...",5,4.10,...,23,18.85,8,6.56,5,4.10,12.5,0.367647,"{'hope': 5, 'love': 23, 'anger': 5, 'sadness':...",2010
3,HUMBLE.,Kendrick Lamar,rap,2017,261,56,21.46,"[pray, crime, finesse, accountant, fact, boo, ...",23,8.81,...,22,8.43,39,14.94,4,1.53,-38.0,-0.678571,"{'hope': 4, 'sadness': 39, 'surprise': 4, 'lov...",2010
4,The Hills,The Weeknd,rb,2015,118,21,17.80,"[friend, found, friend, hide, friend, time, lo...",4,3.39,...,10,8.47,9,7.63,0,0.00,-2.0,-0.095238,"{'love': 10, 'sadness': 9, 'hope': 2, 'anger': 4}",2010

## 장르별 분석

In [63]:
# 장르별 감정 단어 수 합계
genre_count = get_genre_emotion_count(df)
genre_count

         count_anger  count_hope  count_love  count_sadness  count_surprise
genre
country         4855        6825       13286          10743            3876
misc           40227       44945      105624          81570           22158
pop            85882      108330      218586         182129           57883
rap           595523      346500      744304         919824          217867
rb             34576       38631       85631          64265           20575
rock           63110       66842      123015         134692           34915

In [64]:
# 장르별 감정 단어 비율
genre_ratio = get_genre_emotion_ratio(df)
genre_ratio

         count_anger  count_hope  count_love  count_sadness  count_surprise
genre
country     0.122647    0.172414    0.335632       0.271391        0.097916
misc        0.136583    0.152602    0.358626       0.276955        0.075233
pop         0.131557    0.165944    0.334839       0.278992        0.088667
rap         0.210878    0.122698    0.263562       0.325715        0.077148
rb          0.141892    0.158533    0.351410       0.263729        0.084435
rock        0.149347    0.158178    0.291109       0.318742        0.082625

In [65]:
# 장르별 평균 점수
genre_score = get_genre_emotion_score(df)
genre_score

         emotion_score  normalized_emotion_score
genre
country       0.917083                  0.051569
misc          4.845769                  0.032055
pop           0.254579                  0.019000
rap         -17.941505                 -0.330100
rb            1.050861                  0.050337
rock         -3.256652                 -0.133219

In [66]:
# 장르별 Top 10 단어
genre_top_words = get_genre_top_words(df, top_n=10)
genre_top_words

genre    emotion_words
country  love              1136
         time               987
         baby               677
         good               582
         long               360
         friend             261
         leave              255
         hell               225
         god                220
         thought            208
misc     time              3944
         love              2658
         good              2260
         god               1416
         friend            1334
         long              1272
         word              1204
         thought           1129
         shit              1080
         child             1026
pop      love             24749
         time             14128
         baby             12040
         good              5858
         friend            3939
         feeling           3820
         leave             3697
         long              3567
         show              3338
         god               3307
rap      bitch            85791
         shit             67629
         time             35644
         love             35204
         money            29404
         baby             25794
         hit              22225
         real             20421
         good             14504
         god              14286
rb       love             12343
         baby             10548
         time              6305
         shit              2913
         good              2772
         bitch             1923
         real              1886
         leave             1666
         show              1522
         feeling           1495
rock     love              9228
         time              8277
         baby              3027
         good              2608
         long              2484
         friend            2360
         god               2249
         die               2164
         fall              2144
         leave             2110
Name: count, dtype: int64

## 시대별 분석

In [67]:
# 시대별 감정 단어 수 합계
decade_count = get_decade_emotion_count(df)
decade_count

        count_anger  count_hope  count_love  count_sadness  count_surprise
decade
1980          17555       22730       47966          36056           12049
1990          62599       53554      116867         112031           30492
2000          89437       75721      161876         158152           44575
2010         585395      427793      905063         978518          249839
2020         101007       71495      147292         170559           42488

In [68]:
# 시대별 감정 단어 비율
decade_ratio = get_decade_emotion_ratio(df)
decade_ratio

        count_anger  count_hope  count_love  count_sadness  count_surprise
decade
1980       0.128744    0.166696    0.351770       0.264425        0.088364
1990       0.166689    0.142604    0.311195       0.298317        0.081194
2000       0.168825    0.142934    0.305564       0.298535        0.084142
2010       0.186040    0.135954    0.287631       0.310976        0.079399
2020       0.189563    0.134177    0.276428       0.320094        0.079739

In [69]:
# 시대별 평균 점수
decade_score = get_decade_emotion_score(df)
decade_score

        emotion_score  normalized_emotion_score
decade
1980         2.106814                  0.093808
1990        -6.240886                 -0.069275
2000        -5.700798                 -0.086508
2010        -8.722013                 -0.176935
2020       -10.071274                 -0.200020

In [70]:
# 시대별 Top 10 단어
decade_top_words = get_decade_top_words(df, top_n=10)
decade_top_words

decade  emotion_words
1980    love              5726
        time              3002
        baby              2746
        good              1195
        long               904
        word               656
        rock               643
        bad                619
        friend             601
        dance              597
1990    love              7710
        time              5847
        baby              5560
        shit              4411
        bitch             2992
        good              2485
        real              2031
        word              1865
        hit               1774
        long              1720
2000    love             11051
        time              8159
        baby              7299
        shit              6195
        bitch             5058
        good              3690
        money             3202
        real              2964
        show              2527
        hit               2496
2010    bitch            70270
        love             59669
        shit             54810
        time             48242
        baby             37021
        money            25938
        good             20351
        real             19368
        hit              19278
        god              15873
2020    bitch            12895
        love             11665
        shit             10302
        time              8783
        baby              7082
        money             3694
        hit               3660
        good              3309
        real              3145
        bad               3018
Name: count, dtype: int64

### 연도별

In [71]:
# 연도별 감정 단어 수 합계
year_count = get_decade_emotion_count(df, is_year=True)
year_count

      count_anger  count_hope  count_love  count_sadness  count_surprise
year
1980         1987        2327        4792           4029            1148
1981         1218        2093        4091           2784            1070
1982         1215        1788        3775           2480             892
1983         1961        2314        4667           4079            1176
1984         1391        1920        3994           3228            1042
1985         1441        1982        4007           2935            1086
1986         1860        2595        5532           3756            1511
1987         1841        2473        5389           3839            1247
1988         2751        2818        6041           5103            1592
1989         1890        2420        5678           3823            1285
1990         2964        2882        6406           5433            1544
1991         3131        3212        6945           5777            1743
1992         3776        3584        7710           6842            1983
1993         4414        3444        7663           7521            2068
1994         5648        5003       10463          10531            2686
1995         7470        5439       11825          12624            3448
1996         8614        6895       14646          15149            4054
1997         9480        8928       20918          17996            4975
1998         6516        5416       11707          11192            2902
1999        10586        8751       18584          18966            5089
2000         7528        5608       12619          12951            3405
2001         8316        6489       14052          14593            3914
2002         8090        6656       14524          14426            3748
2003         7757        6489       14152          13958            3783
2004         7564        6286       13600          13399            3717
2005         9866        9022       19533          17768            5436
2006         8949        7676       16180          16374            4484
2007         9461        8621       18027          16707            5031
2008         9149        8114       17155          16063            4645
2009        12757       10760       22034          21913            6412
2010        17855       14361       29876          30310            8186
2011        30265       22932       48650          50556           13282
2012        42356       30778       66898          69720           18647
2013        60763       45554       99401         102160           26166
2014        58343       43499       92788          97589           25391
2015        69721       52672      110796         116388           30375
2016        68404       49529      105133         114096           28819
2017        83683       61674      128224         141250           35675
2018        81785       56877      119985         135795           33775
2019        72220       49917      103312         120654           29523
2020        61247       42116       87391         102458           25120
2021        33535       24723       50543          57614           14631
2022         5374        3938        7891           8998            2335
2023          851         718        1467           1489             402

In [72]:
# 연도별 감정 단어 비율
year_ratio = get_decade_emotion_ratio(df, is_year=True)
year_ratio

      count_anger  count_hope  count_love  count_sadness  count_surprise
year
1980     0.139116    0.162921    0.335504       0.282084        0.080375
1981     0.108209    0.185945    0.363451       0.247335        0.095060
1982     0.119704    0.176158    0.371921       0.244335        0.087882
1983     0.138128    0.162992    0.328731       0.287314        0.082834
1984     0.120173    0.165875    0.345054       0.278877        0.090022
1985     0.125841    0.173085    0.349926       0.256309        0.094839
1986     0.121935    0.170119    0.362659       0.246230        0.099056
1987     0.124484    0.167219    0.364392       0.259585        0.084319
1988     0.150287    0.153947    0.330019       0.278776        0.086971
1989     0.125199    0.160307    0.376126       0.253246        0.085122
1990     0.154142    0.149878    0.333143       0.282542        0.080295
1991     0.150471    0.154364    0.333766       0.277634        0.083766
1992     0.158025    0.149990    0.322662       0.286336        0.082988
1993     0.175787    0.137157    0.305177       0.299522        0.082358
1994     0.164516    0.145728    0.304768       0.306749        0.078238
1995     0.183061    0.133289    0.289786       0.309366        0.084497
1996     0.174521    0.139694    0.296730       0.306921        0.082135
1997     0.152174    0.143313    0.335779       0.288874        0.079859
1998     0.172687    0.143535    0.310259       0.296610        0.076909
1999     0.170808    0.141200    0.299858       0.306022        0.082112
2000     0.178766    0.133172    0.299660       0.307544        0.080858
2001     0.175576    0.137003    0.296681       0.308103        0.082637
2002     0.170517    0.140292    0.306129       0.304064        0.078998
2003     0.168122    0.140640    0.306725       0.302521        0.081991
2004     0.169726    0.141049    0.305165       0.300655        0.083404
2005     0.160097    0.146402    0.316966       0.288325        0.088211
2006     0.166763    0.143041    0.301511       0.305126        0.083559
2007     0.163552    0.149031    0.311632       0.288814        0.086971
2008     0.165965    0.147190    0.311196       0.291387        0.084262
2009     0.172681    0.145649    0.298257       0.296619        0.086794
2010     0.177506    0.142771    0.297014       0.301328        0.081381
2011     0.182666    0.138407    0.293629       0.305133        0.080164
2012     0.185447    0.134755    0.292900       0.305255        0.081642
2013     0.181901    0.136371    0.297569       0.305828        0.078331
2014     0.183694    0.136957    0.292144       0.307260        0.079944
2015     0.183499    0.138628    0.291605       0.306323        0.079944
2016     0.186906    0.135332    0.287264       0.311754        0.078745
2017     0.185753    0.136899    0.284622       0.313536        0.079189
2018     0.190990    0.132823    0.280197       0.317117        0.078874
2019     0.192266    0.132890    0.275040       0.321208        0.078597
2020     0.192400    0.132302    0.274528       0.321859        0.078911
2021     0.185229    0.136556    0.279172       0.318229        0.080814
2022     0.188324    0.138001    0.276528       0.315321        0.081826
2023     0.172722    0.145728    0.297747       0.302212        0.081591

In [73]:
# 연도별 평균 점수
year_score = get_decade_emotion_score(df, is_year=True)
year_score

      emotion_score  normalized_emotion_score
year
1980      -0.225746                  0.076646
1981       4.615854                  0.144846
1982       3.554745                  0.149607
1983      -0.788321                  0.077903
1984       1.205036                  0.060859
1985       2.286765                  0.064516
1986       5.035270                  0.101891
1987       3.172819                  0.106552
1988      -1.383562                  0.043712
1989       4.319853                  0.119990
1990      -1.943463                  0.059747
1991      -0.967480                  0.038445
1992      -2.601399                 -0.014743
1993      -5.902778                 -0.040353
1994      -6.076560                 -0.114118
1995     -10.334264                 -0.122889
1996      -9.085737                 -0.095964
1997      -3.899441                 -0.097097
1998      -6.469548                 -0.038164
1999      -9.207402                 -0.130557
2000      -8.207792                 -0.108293
2001      -8.122287                 -0.083155
2002      -6.615603                 -0.096700
2003      -5.682237                 -0.095867
2004      -5.788752                 -0.091390
2005      -4.107551                 -0.074483
2006      -5.914158                 -0.094102
2007      -4.015199                 -0.061165
2008      -4.020101                 -0.068218
2009      -6.185848                 -0.101097
2010      -7.048541                 -0.102559
2011      -9.017857                 -0.153248
2012      -9.358781                 -0.178994
2013      -9.383924                 -0.187323
2014      -9.327287                 -0.182342
2015      -7.877915                 -0.155788
2016      -8.034596                 -0.168817
2017      -8.010702                 -0.169446
2018      -8.976700                 -0.189191
2019      -9.955848                 -0.215115
2020     -10.704378                 -0.213466
2021      -9.343202                 -0.182602
2022      -8.676923                 -0.186778
2023      -6.047059                 -0.083976

In [74]:
# 연도별 Top 10 단어
year_top_words = get_decade_top_words(df, top_n=10, is_year=True)
year_top_words

year  emotion_words
1980  love             517
      time             333
      baby             250
      long             127
      good              91
                      ...
2023  good              71
      god               64
      damn              61
      thought           49
      hit               40
Name: count, Length: 440, dtype: int64

## 아티스트별 분석

In [75]:
# 아티스트별 감정 단어 수 합계
artist_count = get_artist_emotion_count(df, top_n=10)
artist_count

,count_anger,count_hope,count_love,count_sadness,count_surprise
artist,,,,,
2Pac,26.117188,15.156250,28.390625,43.703125,9.316406
Chris Brown,8.751825,7.189781,19.339416,14.832117,4.328467
Drake,11.023529,10.129412,20.708824,17.552941,5.497059
Eminem,23.482143,12.705357,26.107143,39.000000,8.270833
Future,15.586614,8.484252,20.216535,22.956693,5.149606
Juice WRLD,17.009780,8.442543,17.410758,26.124694,5.398533
Kanye West,11.498221,11.234875,23.313167,20.558719,5.814947
Lil Wayne,24.515081,13.925754,28.645012,35.366589,9.470998
Taylor Swift,4.502075,6.775934,13.182573,11.228216,3.780083
YoungBoy Never Broke Again,17.953333,8.240000,18.810000,26.190000,6.480000

In [76]:
# 아티스트별 감정 단어 비율
artist_ratio = get_artist_emotion_ratio(df, top_n=10)
artist_ratio

,count_anger,count_hope,count_love,count_sadness,count_surprise
artist,,,,,
2Pac,0.212882,0.123539,0.231413,0.356226,0.075938
Chris Brown,0.160756,0.132064,0.355232,0.272441,0.079507
Drake,0.169823,0.156049,0.319030,0.270412,0.084685
Eminem,0.214321,0.115961,0.238279,0.355952,0.075488
Future,0.215303,0.117196,0.279258,0.317109,0.071133
Juice WRLD,0.228668,0.113496,0.234059,0.351203,0.072574
Kanye West,0.158771,0.155135,0.321916,0.283882,0.080295
Lil Wayne,0.219034,0.124422,0.255934,0.315989,0.084620
Taylor Swift,0.114066,0.171678,0.333999,0.284483,0.095774
YoungBoy Never Broke Again,0.231139,0.106085,0.242168,0.337181,0.083426

In [77]:
# 아티스트별 평균 점수
artist_score = get_artist_emotion_score(df, top_n=10)
artist_score

                            emotion_score  normalized_emotion_score
artist
2Pac                           -33.851562                 -0.390043
Chris Brown                     -0.649635                  0.016102
Drake                           -2.802941                 -0.042106
Eminem                         -30.022321                 -0.431532
Future                         -14.084646                 -0.289042
Juice WRLD                     -21.502445                 -0.420680
Kanye West                      -3.126335                 -0.036917
Lil Wayne                      -24.273782                 -0.335842
Taylor Swift                     0.840249                  0.052335
YoungBoy Never Broke Again     -21.213333                 -0.426098

In [78]:
# 아티스트별 Top 10 단어
artist_top_words = get_artist_top_words(df, top_n=10, artist_n=10)
artist_top_words

artist                      emotion_words
2Pac                        thug             500
                            time             499
                            shit             494
                            bitch            479
                            die              375
                                            ...
YoungBoy Never Broke Again  baby             264
                            leave            234
                            real             230
                            top              213
                            hit              174
Name: count, Length: 100, dtype: int64

In [79]:
# 아티스트별 감정 변화 추이
artist_name = 'Taylor Swift'  # 원하는 아티스트 이름

trend_count, trend_score = get_artist_emotion_trend(df, artist_name)

display(trend_count)
display(trend_score)

        count_anger  count_hope  count_love  count_sadness  count_surprise
decade
2000             92         174         442            270             122
2010            586         827        1598           1399             449
2020            407         632        1137           1037             340

        emotion_score  normalized_emotion_score
decade
2000         4.771429                  0.246335
2010         0.236607                  0.009095
2020         0.095745                  0.031622

In [80]:
trend_count_year, trend_score_year = get_artist_emotion_trend(df, artist_name, is_year=True)  # 연도별 감정 변화 추이

display(trend_count_year)
display(trend_score_year)

      count_anger  count_hope  count_love  count_sadness  count_surprise
year
2006           26          58         129             68              33
2007            7          11          38             19              12
2008           46          70         172            121              43
2009           13          35         103             62              34
2010           55         146         200            172              67
2011           22          55         111            105              27
2012           91         156         296            237              86
2013           24          22          32             42              10
2014           94         129         249            251              72
2015           20           8          19             30               2
2016            2           3           7              5               2
2017          124         120         291            236              76
2018           19          19          53             43              18
2019          135         169         340            278              89
2020          186         244         405            421             123
2021          204         364         695            564             205
2022            4           7          11             12               2
2023           13          17          26             40              10

      emotion_score  normalized_emotion_score
year
2006       5.818182                  0.291755
2007       4.375000                  0.282407
2008       3.076923                  0.161769
2009       6.500000                  0.311396
2010       3.285714                  0.108622
2011       1.642857                 -0.042291
2012       1.916667                  0.078173
2013      -7.666667                 -0.157680
2014      -1.657895                 -0.081103
2015     -27.000000                 -0.519231
2016       1.500000                  0.136364
2017      -0.500000                 -0.042722
2018       0.166667                  0.024617
2019       0.522727                  0.045899
2020      -2.424242                 -0.098011
2021       1.879310                  0.116833
2022      -1.500000                 -0.055556
2023      -9.250000                 -0.256944

## 저장

In [82]:
# 모든 분석 범주 통합 저장
all_results = {
    'genre': {
        'count': genre_count,
        'ratio': genre_ratio,
        'score': genre_score,
        'top_words': genre_top_words
    },
    'decade': {
        'count': decade_count,
        'ratio': decade_ratio,
        'score': decade_score,
        'top_words': decade_top_words,
        'count_year': year_count,
        'ratio_year': year_ratio,
        'score_year': year_score,
        'top_words_year': year_top_words
    },
    'artist': {
        'count': artist_count,
        'ratio': artist_ratio,
        'score': artist_score,
        'top_words': artist_top_words,
        'trend_count': trend_count,
        'trend_score': trend_score,
        'trend_count_year': trend_count_year,
        'trend_score_year': trend_score_year
    }
}

pd.to_pickle(all_results, '../results/category_analysis.pkl')